package KarelRemote.api;

/*Generated by MPS */


public class CallResponse {
  private Status status;

  public CallResponse(Status status) {
    this.status = status;
  }

  public Status getStatus() {
    return status;
  }
}
