package KarelBasic.sandbox;

/*Generated by MPS */

import JavaKarel.runtime.Script;

public class Test extends Script {


  public void run() {
    robot.step();
    robot.step();
    robot.turnLeft();
  }

  public static void main(String[] args) {
  }
}
