package JavaKarel.runtime;

/*Generated by MPS */


public class Cell {
  public final int CELL_CAPACITY = 8;
  private int marks = 0;
  private boolean wall = false;
  private Robot robot;
  public Cell(boolean wall) {
    this.wall = wall;
  }

  public void setRobot(Robot robot) {
    if (wall) {
      throw new RuntimeException("Robot cannot be placed on a wall.");
    }
    this.robot = robot;
  }
  public void unsetRobot() {
    robot = null;
  }
  public boolean isRobot() {
    return robot != null;
  }

  public Robot getRobot() {
    return robot;
  }

  public void setWall() {
    wall = true;
  }
  public void unsetWall() {
    wall = false;
  }
  public boolean isWall() {
    return wall;
  }


  public void addMark() {
    marks++;
  }
  public void removeMark() {
    marks--;
  }
  public int getMarks() {
    return marks;
  }
  public boolean isFull() {
    return marks == CELL_CAPACITY;
  }
  public boolean isEmpty() {
    return marks == 0;
  }
}
