package JavaKarel.runtime;

/*Generated by MPS */

import cz.dsllp.gui.api.service.GuiService;
import java.net.MalformedURLException;
import java.rmi.RemoteException;
import java.rmi.NotBoundException;
import Common.constants.Comunication;
import java.rmi.Naming;

public class Client {
  private GuiService guiService;

  public void init() throws MalformedURLException, RemoteException, NotBoundException {
    // Call registry for GuiService 
    int port = Comunication.PORT;

    Object srv = Naming.lookup("rmi://localhost:" + String.valueOf(port) + "/GuiService");
    guiService = (GuiService) srv;
  }

  public GuiService getGuiService() {
    return guiService;
  }

}
