package JavaKarel.runtime;

/*Generated by MPS */


public interface RobotGui {

  public void goToPosition(int row, int col);
  public void turnTo(Direction direction);
  public void setMarks(int row, int col, int count);
  public void printMessage(String message);
  public void showAlert(String message);
}
