package JavaKarel.runtime;

/*Generated by MPS */

import cz.dsllp.gui.api.service.GuiService;
import java.rmi.NotBoundException;
import java.net.MalformedURLException;
import java.rmi.RemoteException;
import cz.dsllp.gui.api.message.Step;
import cz.dsllp.gui.api.message.StepSpeed;
import cz.dsllp.gui.api.message.command.ChangeCell;
import cz.dsllp.gui.api.message.command.Position;
import cz.dsllp.gui.api.message.appearance.TextAppearance;
import java.awt.Color;

public abstract class Script {

  protected IRobot robot;

  public Script() {
    Client client = new Client();


    try {
      client.init();

      GuiService guiService = client.getGuiService();

      createWorld(guiService);

      changeCells(guiService);

    } catch (NotBoundException e) {
      e.printStackTrace();
    } catch (MalformedURLException e) {
      e.printStackTrace();
    } catch (RemoteException e) {
      e.printStackTrace();
    }

    robot = new IRobot() {
      public void step() {
      }
      public void turnLeft() {
      }
    };
  }
  public abstract void run();

  private static void changeCells(GuiService gui) throws RemoteException {
    Step step = new Step();
    step.setSpeed(StepSpeed.INSTANT);
    ChangeCell c = new ChangeCell();
    c.setPosition(new Position(2, 3));
    c.setAppearance(new TextAppearance(Color.BLUE, Color.RED, "W"));
    step.add(c);
    gui.doStep(step);
  }
  private static void createWorld(GuiService gui) throws RemoteException {
    gui.createWorld("TestWorld", 10, 12);
  }


}
