package JavaKarel.runtime;

/*Generated by MPS */

import KarelRemote.client.Client;
import java.rmi.NotBoundException;
import java.net.MalformedURLException;
import java.rmi.RemoteException;
import KarelRemote.api.CallResponse;

public abstract class Script {

  protected IRobot robot;

  public Script() {
    /*
      final Client client = new Client();

      try {
        client.init();
      } catch (NotBoundException e) {
      } catch (MalformedURLException e) {
      } catch (RemoteException e) {
      }

      robot = new IRobot() {
        public void step() {
          CallResponse response = client.getRobotService().step();
          System.out.println("Step: " + response.getStatus());
        }
        public void turnLeft() {
          CallResponse response = client.getRobotService().turnLeft();
          System.out.println("Turn left " + response.getStatus());

        }
      };
    */
  }
  public abstract void run();

}
