package JavaKarel.runtime;

/*Generated by MPS */

import KarelRemote.client.Client;
import java.rmi.NotBoundException;
import java.net.MalformedURLException;
import java.rmi.RemoteException;
import KarelRemote.api.RobotService;
import KarelRemote.api.CallResponse;

public abstract class Script {

  protected IRobot robot;

  public Script() {
    final Client client = new Client();

    try {
      client.init();
    } catch (NotBoundException e) {
      e.printStackTrace();
    } catch (MalformedURLException e) {
      e.printStackTrace();
    } catch (RemoteException e) {
      e.printStackTrace();
    }

    robot = new IRobot() {
      public void step() {
        RobotService service = client.getRobotService();

        CallResponse response = service.step();


        System.out.println("Step: " + response.getStatus());
      }
      public void turnLeft() {
        CallResponse response = client.getRobotService().turnLeft();
        System.out.println("Turn left " + response.getStatus());

      }
    };
  }
  public abstract void run();

}
