package JavaKarel.runtime;

/*Generated by MPS */


public class World {
  protected String name;
  protected int width;
  protected int height;
  protected Robot robot;

  private Cell[][] map;

  public World(String name, int height, int width) {
    this.name = name;
    this.width = height;
    this.height = width;
    this.map = new Cell[height][width];

    for (int row = 0; row < height; row++) {
      for (int col = 0; col < width; col++) {
        boolean shouldBeWall = row == 0 || row == height - 1 || col == 0 || col == width - 1;
        map[row][col] = new Cell();
      }
    }

    createWorld1();

  }
  private void createWorld1() {
    map[7][7].addMark();
    map[7][7].addMark();
    // <node> 
    map[5][4].addMark();
  }


  protected void addWall(int row, int col) {
    map[row][col].setWall();
  }
  protected void removeWall(int row, int col) {
    map[row][col].unsetWall();
  }

  protected boolean isAllowedRow(int row) {
    return row > 0 && row < height - 1;
  }
  protected boolean isAllowedCol(int col) {
    return col > 0 && col < width - 1;
  }

  public Cell getCell(int row, int col) {
    // FIXME validate inputs 
    return map[row][col];
  }

  public void addRobot(Robot robot, int row, int col, Direction direction) {
    this.robot = robot;
    robot.instertToWorld(this, row, col, direction);
    map[row][col].setRobot(robot);
  }

  public Robot getRobot() {
    return robot;
  }

  public String getName() {
    return name;
  }

  public int getWidth() {
    return width;
  }
  public int getHeight() {
    return height;
  }

}
