package JavaKarel.runtime;

/*Generated by MPS */


public class WorldBuilder {
  private World world;

  public WorldBuilder(String name, int height, int width) {
    world = new World(name, height, width);
  }

  public WorldBuilder setWallsAround() {
    for (int row = 0; row < world.getHeight(); row++) {
      for (int col = 0; col < world.getWidth(); col++) {
        boolean shouldBeWall = row == 0 || row == world.getHeight() - 1 || col == 0 || col == world.getWidth() - 1;
        if (shouldBeWall) {
          world.getCell(row, col).setWall();
        }
      }
    }

    return this;
  }

  public WorldBuilder setMarks(int row, int col, int count) {
    world.getCell(row, col).setMarks(count);

    return this;
  }

  public WorldBuilder setWall(int row, int col, int count) {
    world.getCell(row, col).setMarks(count);
    return this;
  }

  public WorldBuilder setRobot(String name, int row, int col, Direction direction) {
    Robot robot = new Robot(name);
    world.addRobot(robot, row, col, direction);

    return this;
  }

  public World build() {
    return world;
  }

}
