package KarelBasic.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class CodeBlock_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public CodeBlock_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "KarelBasic.structure.CodeBlock";
  }
}
