package KarelBasic.behavior;

/*Generated by MPS */


public class Step_BehaviorDescriptor extends AbstractCommand_BehaviorDescriptor {
  public Step_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "KarelBasic.structure.Step";
  }
}
