package Common.constants;

/*Generated by MPS */


public interface Comunication {
  public static final int PORT = 12346;
  public static final String SERVICE_NAME = "GuiService";
  public static final String RMI_ADDRESS = "rmi://localhost";
}
