package ViewPlugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.tool.GeneratedTool;
import javax.swing.Icon;
import cz.dsllp.gui.PluginPanel;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.wm.ToolWindowAnchor;
import Common.constants.Comunication;
import cz.dsllp.gui.server.GuiServer;
import javax.swing.JComponent;
import org.apache.log4j.Logger;
import org.apache.log4j.LogManager;

public class KarelView_Tool extends GeneratedTool {
  private static final Icon ICON = null;
  private PluginPanel panel;
  public KarelView_Tool(Project project) {
    super(project, "KarelView", -1, ICON, ToolWindowAnchor.RIGHT, false);
  }
  public void init(Project project) {
    super.init(project);
    KarelView_Tool.this.panel = new PluginPanel();

    KarelView_Tool.this.makeAvailable();

    String serviceName = KarelView_Tool.this.createServiceName();
    if (LOG.isInfoEnabled()) {
      LOG.info(String.format("Initializing GUI panel server on address %s:%s/%s", Comunication.RMI_ADDRESS, Comunication.PORT, serviceName));
    }

    GuiServer server = GuiServer.getInstance();
    server.init(KarelView_Tool.this.panel, Comunication.RMI_ADDRESS, Comunication.PORT, serviceName);

  }
  /*package*/ String createServiceName() {

    return Comunication.SERVICE_NAME;

  }
  public JComponent getComponent() {

    return KarelView_Tool.this.panel;
  }
  protected static Logger LOG = LogManager.getLogger(KarelView_Tool.class);
}
