package ViewPlugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.tool.GeneratedTool;
import javax.swing.Icon;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.wm.ToolWindowAnchor;
import javax.swing.JComponent;
import javax.swing.JPanel;

public class KarelView_Tool extends GeneratedTool {
  private static final Icon ICON = null;
  public KarelView_Tool(Project project) {
    super(project, "KarelView", -1, ICON, ToolWindowAnchor.RIGHT, false);
  }
  public void init(Project project) {
    super.init(project);
    KarelView_Tool.this.makeAvailable();
  }
  public JComponent getComponent() {
    JPanel panel = new JPanel();
    return panel;
  }
}
