package ViewPlugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.tool.GeneratedTool;
import javax.swing.Icon;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.wm.ToolWindowAnchor;
import KarelRemote.server.Server;
import java.rmi.AlreadyBoundException;
import java.net.MalformedURLException;
import java.rmi.RemoteException;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.JLabel;

public class KarelView_Tool extends GeneratedTool {
  private static final Icon ICON = null;
  private String message = "init message";
  public KarelView_Tool(Project project) {
    super(project, "KarelView", -1, ICON, ToolWindowAnchor.RIGHT, false);
  }
  public void init(Project project) {
    super.init(project);
    KarelView_Tool.this.makeAvailable();
    KarelView_Tool.this.message = "init...";

    try {
      Server server = new Server();
      server.init();
      KarelView_Tool.this.message = server.toString();

    } catch (AlreadyBoundException e) {
      e.printStackTrace();
      KarelView_Tool.this.message = e.toString();
    } catch (MalformedURLException e) {
      e.printStackTrace();
      KarelView_Tool.this.message = e.toString();

    } catch (RemoteException e) {
      e.printStackTrace();
      KarelView_Tool.this.message = e.toString();

    }


  }
  public JComponent getComponent() {

    JPanel panel = new JPanel();
    JLabel label = new JLabel(KarelView_Tool.this.message);
    panel.add(label);
    return panel;
  }
}
