package KarelRemote.server;

/*Generated by MPS */

import java.rmi.server.UnicastRemoteObject;
import KarelRemote.api.RobotService;
import java.rmi.RemoteException;
import KarelRemote.api.CallResponse;
import KarelRemote.api.Status;

public class RobotServiceImpl extends UnicastRemoteObject implements RobotService {

  public RobotServiceImpl() throws RemoteException {
    super();
  }
  public CallResponse step() {
    print("step");

    CallResponse response = new CallResponse(Status.SUCCESS);

    return response;
  }

  public CallResponse turnLeft() {
    print("turn left");

    CallResponse response = new CallResponse(Status.SUCCESS);

    return response;
  }

  private void print(String msg) {
    System.out.println("Server :" + msg);
  }
}
