package KarelRemote.server;

/*Generated by MPS */

import java.rmi.AlreadyBoundException;
import java.rmi.RemoteException;
import java.net.MalformedURLException;
import java.rmi.RMISecurityManager;
import java.rmi.Naming;
import KarelRemote.api.RobotService;

public class Server {

  private RobotServiceImpl robotService;

  public void init() throws AlreadyBoundException, RemoteException, MalformedURLException {
    // Assign a security manager, in the event that dynamic 
    // classes are loaded 
    /*
      if (System.getSecurityManager() == null) {
        System.setSecurityManager(new RMISecurityManager());
      }
    */
    // Create an instance of our power service server ... 
    robotService = new RobotServiceImpl();
    Naming.bind("RobotService", robotService);
    System.out.println("Service bound....");


  }


  public RobotService getRobotService() {
    return robotService;
  }
}
